# Logging settings
debug=true
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.com.github.nnbros.rtp=DEBUG
logging.file.path=
logging.file.name=