spring.application.name=gateway
#####
# Network settings
#####
server.port=443
spring.ssl.bundle.pem.rtp.keystore.certificate=classpath:/certificates/${gateway.certificate-name}
spring.ssl.bundle.pem.rtp.keystore.private-key=./certificates/rtpbot.key
spring.ssl.bundle.pem.rtp.truststore.certificate=classpath:/certificates/root.crt
server.ssl.enabled=true
server.ssl.bundle=rtp
#####
# Logging settings
#####
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.file.name=/var/log/rtp/gateway/gateway.log
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} : %X{chatId} %X{updateId} %m%n%wEx
#####
# Bot settings
#####
gateway.rtp-bot.url=https://rtp-bot.ru:8443
gateway.rtp-bot.ip=93.120.241.248
gateway.rtp-bot.webhook-path=rtp
gateway.rtp-bot.token=${RTP_BOT_TOKEN}
gateway.certificate-name=rtpbot-chain.crt
gateway.certificate-path=/certificates/${gateway.certificate-name}
